parameters:
    oro_report.report.entity.class:                    Oro\Bundle\ReportBundle\Entity\Report
    oro_report.form.type.report.class:                 Oro\Bundle\ReportBundle\Form\Type\ReportType
    oro_report.form.type.entity_choice.class:          Oro\Bundle\ReportBundle\Form\Type\ReportEntityChoiceType
    oro_report.form.type.chart_choice.class:           Oro\Bundle\ReportBundle\Form\Type\ReportChartChoiceType
    oro_report.form.handler.report.class:              Oro\Bundle\ReportBundle\Form\Handler\ReportHandler
    oro_report.report.manager.api.class:               Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager

services:
    oro_report.form.type.report:
        class: %oro_report.form.type.report.class%
        tags:
            - { name: form.type, alias: oro_report }

    oro_report.form.report:
        class:           Symfony\Component\Form\Form
        factory_method:  createNamed
        factory_service: form.factory
        arguments:
            - "oro_report_form"
            - "oro_report"

    oro_report.form.handler.report:
        class: %oro_report.form.handler.report.class%
        scope: request
        arguments:
            - @oro_report.form.report
            - @request
            - @doctrine.orm.entity_manager

    oro_report.report.manager.api:
        class: %oro_report.report.manager.api.class%
        arguments:
            - %oro_report.report.entity.class%
            - @doctrine.orm.entity_manager

    oro_report.form.type.entity_choice:
        class: %oro_report.form.type.entity_choice.class%
        arguments:
            - @oro_report.entity_provider
        tags:
            - { name: form.type, alias: oro_report_entity_choice }

    oro_report.form.type.chart_choice:
        class: %oro_report.form.type.chart_choice.class%
        arguments:
            - @oro_chart.config_provider
        tags:
            - { name: form.type, alias: oro_report_chart_choice }
