oro_system_configuration:
    groups:
        reports_settings:
            title: oro.report.system_configuration.groups.report_settings.title
    fields:
        oro_report.display_sql_source_code:
            data_type: boolean
            type: oro_config_checkbox
            options:
                label: oro.report.system_configuration.fields.display_sql_source_code.label
                tooltip: oro.report.system_configuration.fields.display_sql_source_code.tooltip
                required: true
                resettable: true

    tree:
        system_configuration:
            platform:
                children:
                    general_setup:
                        children:
                            look_and_feel:
                                children:
                                    reports_settings:
                                        priority: -10
                                        children:
                                            - oro_report.display_sql_source_code
        organization_configuration:
            platform:
                children:
                    general_setup:
                        children:
                            look_and_feel:
                                children:
                                    reports_settings:
                                        priority: -10
                                        children:
                                            - oro_report.display_sql_source_code
